# Generated by Django 4.0.6 on 2022-11-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(default='Name of the crime scene', max_length=200)),
                ('case_desc', models.TextField(default='Add description here')),
                ('case_date', models.DateField()),
                ('case_loc', models.CharField(default='Delhi', max_length=70)),
                ('case_cover', models.FileField(default='media/case/n.png', upload_to='media/case')),
                ('case_category', models.CharField(choices=[('1', 'Robbery'), ('2', 'Murder'), ('3', 'Kidnapping'), ('4', 'Theft'), ('5', 'Threat'), ('6', 'Burglary')], default='Robbery', max_length=50)),
                ('case_criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal.criminal')),
            ],
        ),
    ]
