# Generated by Django 4.0.6 on 2022-11-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27)),
                ('image', models.FileField(null=True, upload_to='criminal')),
                ('location', models.TextField(max_length=200, null=True)),
                ('pnum', models.IntegerField(null=True)),
            ],
        ),
    ]
